### ISSUE TITLE
你好，请教一个问题，我怎么关闭光标所在位置有下划线的功能，我能把文本里的下划线样式换成光标所在位置的下划线样式吗？

### ISSUE THREAD

**Issue by LCYeo1** [passwordgloo/Typora-foresee-theme#5]

**Comment by passwordgloo** [comment]
**可以的**

光标下设置下划线方便专注模式下预览，不喜欢可直接删除代码，修改样式可用记事本编辑📁source下的`foresee.min.css`，定位到以下代码：

```css
p.md-focus>span.md-plain.md-expand {
    border-bottom: 2px dashed var(--focus-color);
    color: var(--focus);
}
```
修改为
```css
p.md-focus>span.md-plain.md-expand {
    border-bottom: 1px solid var(--focus-color);
    color: var(--focus);
}
```

`var(--focus-color)`颜色定义在*_dark(light).css文件

```css
:root {
   ……
    --focus-color: #00CD66;
   ……
}
```
