### ISSUE TITLE
代码块能否取消默认第一行选择状态光标

### ISSUE THREAD

**Issue by fyozt** [passwordgloo/Typora-foresee-theme#7]
代码块能否取消默认第一行选择状态光标，输入在那行在显示光标选择行

**Comment by passwordgloo** [comment]
出于简约化考虑，要么在代码块每行点击后都显示光标，要么全部不显示。
打开codeLight.min.css或者codeDark.min.css修改如下代码可取消代码块光标显示

```css
.CodeMirror div.CodeMirror-cursor {
    border-left:solid 2px var(--theme-color)
    visibility: hidden;
}
```
